Adding sanity check to ChannelManager.disconnectChannel...
... which leads to a testfailure that indicates that there is a race (or
similar problem) in Channel.close:

java.lang.IllegalStateException: We have attempted to create a disconnect a channel that's no longer in use. This should never happen. Please report this as a bug.
	at com.rabbitmq.client.impl.ChannelManager.disconnectChannel(ChannelManager.java:130)
	at com.rabbitmq.client.impl.AMQConnection.disconnectChannel(AMQConnection.java:117)
	at com.rabbitmq.client.impl.ChannelN.releaseChannelNumber(ChannelN.java:169)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:365)
	at com.rabbitmq.client.impl.ChannelN.abort(ChannelN.java:307)
	at com.rabbitmq.client.impl.ChannelN.abort(ChannelN.java:300)
	at com.rabbitmq.client.test.BrokerTestCase.closeChannel(BrokerTestCase.java:124)
	at com.rabbitmq.client.test.BrokerTestCase.tearDown(BrokerTestCase.java:67)